import { type NextPage } from "next";
import { api } from "../utils/api";
import Head from "next/head";
import { OperatorCard } from "../components/OperatorCard";

const Home: NextPage = () => {
  const mutation = api.operator.getOperator.useMutation();

  const pickOperator = (role: string) => {
    const random = Math.floor(Math.random() * (33 - 1 + 1) + 1);
    mutation.mutate({ id: random, role: role });
  };

  if (!mutation.data) {
    return (
      <>
        <Head>
          <title>Random Operator</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="h-[100vh] bg-background bg-cover bg-center bg-no-repeat ">
          <div className="p-16 text-center text-5xl text-white">
            Pick operator
          </div>
          <div className="flex flex-col items-center justify-center">
            <div className="flex flex-row">
              <div className="p-2">
                <button
                  onClick={() => pickOperator("attacker")}
                  className="h-[150px] w-[150px] rounded-xl bg-attackerButton bg-cover text-white"
                ></button>
              </div>
              <div className="p-2">
                <button
                  onClick={() => pickOperator("defender")}
                  className="h-[150px] w-[150px] rounded-xl bg-defenderButton bg-cover text-white"
                ></button>
              </div>
            </div>
            <div className=""></div>
          </div>
        </main>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Random Operator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="p-16 text-center text-5xl text-white">
          Pick operator
        </div>
        <div className="flex flex-col items-center justify-center">
          <div className="flex flex-row">
            <div className="p-2">
              <button
                onClick={() => pickOperator("attacker")}
                className="h-[150px] w-[150px] rounded-xl bg-attackerButton bg-cover text-white"
              ></button>
            </div>
            <div className="p-2">
              <button
                onClick={() => pickOperator("defender")}
                className="h-[150px] w-[150px] rounded-xl bg-defenderButton bg-cover text-white"
              ></button>
            </div>
          </div>
          <div className="">
            <OperatorCard
              name={mutation.data?.name!}
              icon={mutation.data?.icon!}
              card={mutation.data?.card!}
            />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
